# Generated by Django 5.0.7 on 2024-07-16 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storename', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StoreSnack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('snack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.snack')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_snacks', to='app2.store')),
            ],
        ),
    ]
