# Generated by Django 5.0.7 on 2024-07-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_product_supremarket'),
    ]

    operations = [
        migrations.AddField(
            model_name='supremarket',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='supremarket',
            name='invoiceno',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supremarket',
            name='storename',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supremarket',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='supremarket',
            name='pieces',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='supremarket',
            name='units',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
