# Generated by Django 5.0.7 on 2024-07-23 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_supremarket_date_supremarket_invoiceno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supremarket',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='app2.product'),
        ),
    ]
