# Generated by Django 5.0.7 on 2024-07-14 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='stroename',
            new_name='storename',
        ),
    ]
