# Generated by Django 5.0.2 on 2024-07-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_stroename_store_storename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='snacks',
        ),
        migrations.AddField(
            model_name='store',
            name='snacks',
            field=models.ManyToManyField(to='app.snacks'),
        ),
    ]
